version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn my_digital_wallet.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    environment:
      - DEBUG=1
      - SECRET_KEY=foo
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=django_docker_prod
      - SQL_USER=django_docker
      - SQL_PASSWORD=django_docker
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
      # - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_docker
      - POSTGRES_PASSWORD=django_docker
      - POSTGRES_DB=django_docker_prod

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
